### ISSUE TITLE
Fix links to 1D input files

### ISSUE THREAD

**Issue by mrp089** [SimVascular/simvascular.github.io-archive#119]
@CZHU20 found that the links to the 1D input files in the ROM simulation guide are no longer working because we moved them to [a different folder](https://github.com/SimVascular/svOneDSolver/tree/master/tests/cases). There are two occasions of 

> The complete 1D Simulation input file is available

@ktbolt I tried to fix them myself but I didn't understand the edit/build instructions. Thank you!!

**Comment by ktbolt** [comment]
@mrp089 You should have seen the edit/build instructions before I simplified them! I will add the links.

**Comment by ktbolt** [comment]
I have fixed the links and merged into master.
