### ISSUE TITLE
Receiving Access to Simvascular Supercomputing Gateway

### ISSUE THREAD

**Issue by dcuster2020** [SimVascular/simvascular.github.io-archive#34]
I am a student at Clemson University and requested access to the Simvascular Supercomputing Gateway last week in order to run CFD's with Simvascular models. What is the normal timeline to expect for being approved?

Thanks,
Daniel Custer

**Comment by ktbolt** [comment]
@dcuster2020 I have added you to the Gateway.

**Comment by dcuster2020** [comment]
Thank you very much!

Best regards,
Daniel

Daniel L. Custer CLEMSON UNIVERSITY

Department of Mechanical Engineering
Calhoun Honors College
Cell: (864) 364-4734
