### ISSUE TITLE
Add documentation for the 1D Simulation Tool and 1D Solver.

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/simvascular.github.io-archive#5]
Documentation describing the SimVascular 1D Simulation Tool and 1D Solver needs to be added to the SimVascular web site.

**Comment by ktbolt** [comment]
I've started on this, added a **1D Simulation** entry under User Guides documentation.

<img width="1640" alt="1d-sim-web-doc" src="https://user-images.githubusercontent.com/23109458/63396386-b5ccc380-c37b-11e9-9ca4-525fe7983f43.png">

**Comment by ktbolt** [comment]
I've added more documentation for the 1d simulation tool, finishing up the sub-panels.

<img width="1657" alt="1d-sim-tool" src="https://user-images.githubusercontent.com/23109458/63569180-1ea76d80-c52d-11e9-9455-26eb27a9913d.png">

**Comment by ktbolt** [comment]
I've finished adding the 1D Simulation Tool user documentation, will make another pass though it to add a bit more information. I will next add a tutorial.

I've also added the 1D solver theory section, taken from the OneDSolver content. It took some time to convert the 13 pages of equations into a format that MathJax can understand. I'll need to spend some more time cleaning up the formatting.

**Comment by ktbolt** [comment]
I've added 1d solver input file format, need to clean up a bit, remove references to **card**.

<img width="1666" alt="Screen Shot 2019-08-25 at 3 00 49 PM" src="https://user-images.githubusercontent.com/23109458/63656486-3bb88800-c749-11e9-8578-8d090e6b77e4.png">

**Comment by ktbolt** [comment]
I've added equation numbers, equation references and fixed display of matrix equations to the 1d solver theory section. There were lots of incompatibilities with the SV web docs markup, problems getting matrix equations to work, etc.

**Comment by ktbolt** [comment]
Cleaned up 1d solver input file format doc.

**Comment by ktbolt** [comment]
I've added tutorials for the 1D Simulation Tool and 1D Solver.

<img width="1579" alt="solver-1d-tut" src="https://user-images.githubusercontent.com/23109458/64059705-80dc2000-cb76-11e9-8c8b-732980aa301f.png">

**Comment by ktbolt** [comment]
The 1D Solver theory documentation is excellent but there is no documentation discussing the details of the 1D Solver input file, how to choose time step, quadrature points, segments, joints, etc.

There is also no documentation describing the Python package used to generated solver input files from centerlines geometry.

**Comment by ktbolt** [comment]
I've mostly finished the 1D Solver User Guide, will maybe add a bit more information. 

<img width="1172" alt="Screen Shot 2019-09-13 at 10 05 04 PM" src="https://user-images.githubusercontent.com/23109458/64903718-c0286780-d672-11e9-96d6-78b0019859a5.png">

**Comment by alisonmarsden** [comment]
This looks great.   A couple small things to fix: 
- the "download" item is not clickable and does not have anything under it 
- the sidebar text (such as "1D simulation guide" overlaps with the main text when the browser is not full screen.

**Comment by ktbolt** [comment]
I am putting together a sample project for the **download**, need to figure out how to add new files to the downloads SimTK.

The other sections that have long titles have this same problem (e.g. Simulation Guide). I'll see if I can set the width of the sidebar text.

**Comment by alisonmarsden** [comment]
I just added you as an admin on the simtk examples project.  You should now be able to add files.

---------------------------------------------------------------
Alison Marsden
Associate Professor
Departments of Pediatrics and Bioengineering, and by courtesy of Mechanical Engineering
Institute for Computational and Mathematical Engineering
Vera Moulton Wall Center Faculty Scholar
Stanford University
amarsden@stanford.edu
https://cbcl.stanford.edu/
www.simvascular.org<http://www.simvascular.org>
