### ISSUE TITLE
Add Python interface to documentation menu

### ISSUE THREAD

**Issue by alisonmarsden** [SimVascular/simvascular.github.io-archive#65]
The link to the python interface is missing from the menu at the top of the documentation pages.   It should be added as a link in the menu bar under user guides at the top of this page:  http://simvascular.github.io/docsPythonInterface.html

**Comment by ktbolt** [comment]
I've added a Python Interface menu item, up on the website now.
<img width="801" alt="Screen Shot 2021-02-24 at 1 59 37 PM" src="https://user-images.githubusercontent.com/23109458/109076705-de8bf280-76af-11eb-8551-14a48d3dcab6.png">
