### ISSUE TITLE
Add link to youtube tutorials in SV documentation

### ISSUE THREAD

**Issue by alisonmarsden** [SimVascular/simvascular.github.io-archive#66]
The tutorial videos on the SV youtube channel may be quite useful to the user community and the link should be featured more prominently in the documentation. The SV youtube channel is here:  https://www.youtube.com/channel/UCT61XgTRqpfb39Hyio9IqGQ
These were created in the summer of 2020 and have already had quite a few views.

**Comment by ktbolt** [comment]
I've added an `Online Tutorials` tab to the main web page. Note that I had to shorten `Our Team` to `Team` to get the new tab to fit, spent one hour trying to figure out how to expand the top menu; forgetaboutit!

<img width="1288" alt="Screen Shot 2021-06-14 at 10 48 18 AM" src="https://user-images.githubusercontent.com/23109458/121936089-17eb7b00-ccfe-11eb-9dea-8f69eaf515bc.png">

Clicking on that brings you to 
<img width="1316" alt="Screen Shot 2021-06-14 at 10 49 19 AM" src="https://user-images.githubusercontent.com/23109458/121936224-41a4a200-ccfe-11eb-82b3-299d70b7800c.png">


Merged into the master branch.
