### ISSUE TITLE
Change the 1D Simulation Guide to the Reduced-Order Model Guide

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/simvascular.github.io-archive#69]
1D Simulations plugin has been renamed to the **Reduced-Order Model Simulation** plugin. This plugin now supports both 1D and 0D simulations.

**Comment by ktbolt** [comment]
@mrp089 @JonathanPham I need to add documentation for the 0D solver. In the **Intro** I will have something like

<img width="1496" alt="Screen Shot 2021-05-18 at 10 03 53 PM" src="https://user-images.githubusercontent.com/23109458/118759015-fdb89d00-b824-11eb-9996-25b504183b1e.png">

I now need to add documentation for the 0D solver, similar to the 1D Solver I guess

<img width="1461" alt="Screen Shot 2021-05-18 at 10 02 26 PM" src="https://user-images.githubusercontent.com/23109458/118759184-61db6100-b825-11eb-979d-797516c87df0.png">

At some point I would like to put  the 1D Solver and the 0D Solver documentation in their own sections outside of the ROM Simulation Guide.  But for now I will include it there. 

I need you guys to provide me with documentation: text, images and equations. Any suggestions about how to organize the documentation would be helpful.

**Comment by JonathanPham** [comment]
@ktbolt @mrp089 I invited you guys to an Overleaf document (via Stanford email), where I am currently writing up the requested documentation (including text, figures, and equations) for the 0D Solver. 

@ktbolt Once I am done writing, you can grab the text, images, and equations that you need for the ROM Simulation Guide directly from the Overleaf doc.

**Comment by ktbolt** [comment]
@JonathanPham You will need to add the 0D Solver SV documentation directly to MarkDown files used to generate the SV web documentation. Creating the documentation in some other format and then trying to add it later takes too much effort to get it right.

I've created a section where you can add the documentation here https://github.com/ktbolt/simvascular.github.io/tree/1D-Simulation-Guide-to-ROM-Guide_69/source/documentation/rom_simulation/0d-solver. 

You can clone my branch and make changes to that. Have a look here https://github.com/SimVascular/simvascular.github.io to see how to view the documentation locally in a browser.

The documentation uses MathJax for equations which is not 100% compatible with LaTeX (see http://docs.mathjax.org/en/latest/input/tex/html.html).

**Comment by JonathanPham** [comment]
@ktbolt Sounds good! I will add the documentation to my fork https://github.com/JonathanPham/simvascular.github.io/tree/1D-Simulation-Guide-to-ROM-Guide_69

**Comment by ktbolt** [comment]
@JonathanPham The methods used to create SV documentation are a bit obscure but if you just follow the `1D Simulation` docs you should be OK. The `ROM Simulation` table of contents are defined in  
```
simvascular.github.io/source/documentation/_rom_simulation_TOC.erb
simvascular.github.io/source/documentation/_rom_simulation_content.erb
```

Note that you can use MarkDown or html in the docs.
