### ISSUE TITLE
Clean up documentation removing old content and links, fixing links, fix menus 

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/simvascular.github.io-archive#70]
We need to do a simple clean up of the documentation 

1) Remove old content

2) Fix installation links

3) Fix menus

**Comment by ktbolt** [comment]
I've fixed some links and menus, and added a `Online Tutorials` header to the home page.
<img width="1288" alt="Screen Shot 2021-06-03 at 9 35 45 PM" src="https://user-images.githubusercontent.com/23109458/120746263-b2a0ba00-c4b3-11eb-8654-7254d5f6a62c.png">

I am now rewriting the `Quick Guide` section, will simplify, change `HINTS` in red font to something less alarming, remove the `DICOM Images` section that explains how to read in images that will totally screw you, and spell SimVascular correctly.

**Comment by alisonmarsden** [comment]
Dave, While you’re at it, can you update the “workshops” section for 2021?


From: Dave Parker ***@***.***>
Date: Thursday, June 3, 2021 at 9:48 PM
To: SimVascular/simvascular.github.io ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [SimVascular/simvascular.github.io] Clean up documentation removing old content and links, fixing links, fix menus (#70)

I've fixed some links and menus, and added a Online Tutorials header to the home page.
[Screen Shot 2021-06-03 at 9 35 45 PM]<https://user-images.githubusercontent.com/23109458/120746263-b2a0ba00-c4b3-11eb-8654-7254d5f6a62c.png>

I am now rewriting the Quick Guide section, will simplify, change HINTS in red font to something less alarming, remove the DICOM Images section that explains how to read in images that will totally screw you, and spell SimVascular correctly.

**Comment by ktbolt** [comment]
@alisonmarsden I will update the workshops section for 2021.

**Comment by ktbolt** [comment]
I've rewritten most of the Introduction, finishing up the GUI section, documenting how the display menus work which even the MITK documentation does not explain!

<img width="1686" alt="Screen Shot 2021-07-06 at 10 55 11 PM" src="https://user-images.githubusercontent.com/23109458/124707162-4b5c9800-dead-11eb-8a37-6085cb9e85be.png">


No matter what some may think, creating html pages using a text editor is the way to go!

**Comment by ktbolt** [comment]
I've finished the GUI `Display` section

<img width="1630" alt="Screen Shot 2021-07-07 at 8 32 06 PM" src="https://user-images.githubusercontent.com/23109458/124858241-88cf2d00-df62-11eb-9b5d-a5fe0b14ff77.png">

There is more work to do for the GUI `Data Manager` section, will do that next.

**Comment by ktbolt** [comment]
I've finished (for now) the GUI `Data Manager` and `Tool Panel`
<img width="1630" alt="Screen Shot 2021-07-09 at 9 16 15 PM" src="https://user-images.githubusercontent.com/23109458/125151444-0332b500-e0fb-11eb-8f77-9f3c463cd524.png">

As I write the documentation I am realizing how confusing the SV GUI is and how it doesn't work like other apps. This makes it more difficult and time consuming to document. 

For example,  the `SV Path Planning` and `SV Modeling` tabs in the Tool Panel scream out to you that you can switch between the `SV Path Planning` and `SV Modeling` Tool Panels. 

<img width="430" alt="Screen Shot 2021-07-09 at 9 22 47 PM" src="https://user-images.githubusercontent.com/23109458/125151556-de8b0d00-e0fb-11eb-9175-b47599e4c55f.png">

But no, selecting the `SV Path Planning` tab brings up this

<img width="430" alt="Screen Shot 2021-07-09 at 9 26 34 PM" src="https://user-images.githubusercontent.com/23109458/125151631-6113cc80-e0fc-11eb-9958-0e93799e87f5.png">

To show the `SV Path Planning` panel you must click in the Data Manager. Why even have those misleading tabs?

**Comment by ktbolt** [comment]
I've started the `Tutorial` section, using a table format to show the GUI and describing the inputs
<img width="1630" alt="Screen Shot 2021-07-12 at 8 59 55 PM" src="https://user-images.githubusercontent.com/23109458/125388450-5bb0bf00-e354-11eb-9bde-98669e321f48.png">

I think this format will be OK. 

What is really missing is a `User Manual` that describes all the controls for each `Tool`. That will be a lot more work, especially since it is not clear what many of the GUI controls do.

**Comment by ktbolt** [comment]
I've finished the `Tutorial` so I'm done with the first pass at this.

<img width="1621" alt="Screen Shot 2021-08-03 at 4 41 55 PM" src="https://user-images.githubusercontent.com/23109458/128099819-e8a9659b-75d2-4f52-9234-8c862ff8385e.png">

I'll now do a spell check and check for consistency and clarity.

**Comment by ktbolt** [comment]
I've fixed spelling mistakes and added a bit more content.

The source and master branches have been merged so it is now live!
