### ISSUE TITLE
Integrate SimCardio Guide 

### ISSUE THREAD

**Issue by ktbolt** [SimVascular/simvascular.github.io-archive#83]
Ignoring the README here that states `DO NOT edit the master branch files!` and not followiing the existing documentation practices the initial `SimCardio Guide`  documentation was incorrectly added to the `master` branch as html. That was later moved into `.erb` files but the documentation does not display correctly. 

I will add the files to the `source` branch and see if I can get the documentation to display correctly.

**Comment by ktbolt** [comment]
I've added the `SimCardio` section 
<img width="529" alt="Screen Shot 2021-06-14 at 11 47 13 AM" src="https://user-images.githubusercontent.com/23109458/121943350-57b66080-cd06-11eb-8baf-ef34fcdbbd4a.png">

But this is what it looks like

<img width="1630" alt="Screen Shot 2021-06-14 at 11 46 04 AM" src="https://user-images.githubusercontent.com/23109458/121943394-63098c00-cd06-11eb-93f8-7e08a31e0fdd.png">

**Comment by ktbolt** [comment]
I've fixed the major formatting problems and cleaned up the `Cardiac Geometric Modeling Tool` section a bit, still needs a lot or work though, not very clear what it is and what it does, how to use it, what the outputs are, etc. 

<img width="1564" alt="Screen Shot 2021-06-14 at 6 59 21 PM" src="https://user-images.githubusercontent.com/23109458/121981633-e77a0000-cd42-11eb-8614-f6710bd070e2.png">

**Comment by ktbolt** [comment]
The equations in the `electrophysiology` section were not in the correct **MathJax** format and contained `_` symbols that needed to be escaped. 

I fixed all that and now the equations are looking good
<img width="1564" alt="Screen Shot 2021-06-14 at 9 45 23 PM" src="https://user-images.githubusercontent.com/23109458/121994609-6c244880-cd5a-11eb-9a41-b30feb26eb8b.png">

**Comment by vvedula22** [comment]
Great! once you are done fixing these issues, I will work on editing the content.

**Comment by ktbolt** [comment]
I've merged my changes into the `source` branch.

@vvedula22 I removed the `simcardio/electrophysiology/images/ttp_cuboid.gif` file, at 17M a bit large to put in GitHub.

**Comment by CZHU20** [comment]
@ktbolt Hi Dave, I just submitted a pull request, which should fix the equation display in cardiac mechanics modeling section. Please let me know if there is any issue.

Another suggestion is to replace the Purkinje network visualization (https://simvascular.github.io/documentation/simcardio/electrophysiology/images/purkinje-paraview.png) with a newer one. This one does not look physiologically correct as the fibers branched into the aortic region. @vvedula22 should have some better results. 

Thanks.
